$include:
  - conf/217/base217.yml
  - conf/217/1gpu217.yml 

num_iters: 500000  
save_iters: []

## 개당=> ㅇㅇ. 16/4 = 개당 4. => 대충 몇 정도?
## 개당 8 => 다른 gpu에선 20000 먹었음.
## 개당 6 해 봅시다. => 총 24
batch_size: 32
val_batch_size: 8

## ALMOST COSINE

## 4 = 32 * 0.125

DACImpGrad.quantizer_dropout: 0.0  ####! 0
DACImpGrad.full_codebook_rate: 0.07 ####! 1, 6.25%

DACImpGrad.use_framewise_masking: false

DACImpGrad.n_codebooks: 8
DACImpGrad.imp_model_ver: "v2_2"
DACImpGrad.random_level: 6.0  ####!  x2, x4
DACImpGrad.random_range: 0
DACImpGrad.imp2mask_alpha: 1  ###$
DACImpGrad.imp2mask_func: "logcosh_ref"  # 'sigmoid', 'tanh', 'square' ###$
DACImpGrad.train_impmap_only: true
load_pretrained: true
# DACImpGrad.imp2mask_shift: 0.0  ## =ref

lambdas: ## For generator. 
  mel/loss: 15.0
  # mel/loss_l2: 0.0  ####!
  # l2/loss: 2.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0
  vq/rate_loss: 10  ####!
        ## [0.0001, 0.2] * 15 * 33 = [0.05, 100.]
  vq/rate_threshold: 0 ####!


train/AudioLoader.shuffle: true
train/AudioLoader.ext: 
  - drums.wav
val/AudioLoader.ext: 
  - drums.wav
test/AudioLoader.ext: 
  - drums.wav

train/build_dataset.folders:
  music_hq:
    - /data2/woosung/repos/musdb18hq_from_zenodo/train

val/build_dataset.folders:
  music_hq:
    - /data2/woosung/repos/musdb18hq_from_zenodo/test
  # general:
  #   - /data/woosung/musicdata/AudioSet/wav22k/test

test/build_dataset.folders:
  music_hq:
    - /data2/woosung/repos/musdb18hq_from_zenodo/test
  # general:
  #   - /data/woosung/musicdata/AudioSet/wav22k/test