$include:
  - conf/base.yml
  - conf/1gpu.yml

amp: false
batch_size: 2
val_batch_size: 2
num_workers: 8


num_iters: 500000
save_iters: []

DAC.quantizer_dropout: 0.5

# resume: true
# tag: 'best'
# load_weights: true


## eval pretrained dac
# resume: false
# load_weights: false
# load_pretrained: true
