$include:
  - conf/base.yml
  - conf/1gpu.yml

amp: true
batch_size: 16
val_batch_size: 16

num_iters: 400000
save_iters: []

DAC.quantizer_dropout: 0.1
DAC.full_codebook_rate: 0.1
DAC.alpha_dist: 1.0
