$include:
  - conf/base.yml
  - conf/1gpu.yml

num_iters: 800000
save_iters: []

batch_size: 8
val_batch_size: 8

### 달랐던건, full_codebook_rate=0, random_level=None이었단 것.
DACImpGrad.quantizer_dropout: 0.25  # 2
DACImpGrad.full_codebook_rate: 0.2 # 1
DACImpGrad.use_framewise_masking: false

DACImpGrad.n_codebooks: 8
DACImpGrad.imp_model_ver: "v2_1"
DACImpGrad.random_level: 8.0
DACImpGrad.random_range: 0

lambdas: ## For generator. 
  mel/loss: 15.0
  mel/loss_l2: 0.0
  # l2/loss: 2.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0
  vq/rate_loss: none  ## [0.0001, 0.2] * 15 * 33 = [0.05, 100.]
  vq/adaptive_rate_loss: true
  vq/rate_threshold: 0

# Loss setup

MelSpectrogramLossDuplicate.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLossDuplicate.window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
MelSpectrogramLossDuplicate.mel_fmin: [0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLossDuplicate.mel_fmax: [null, null, null, null, null, null, null]
MelSpectrogramLossDuplicate.pow: 1.0
MelSpectrogramLossDuplicate.clamp_eps: 1.0e-5
MelSpectrogramLossDuplicate.mag_weight: 0.0
# resume: true

# resume: true
# load_weights: true
# tag: 'latest'
