$include:
  - conf/base.yml
  - conf/1gpu.yml

amp: true
batch_size: 16
val_batch_size: 16

num_iters: 400000
save_iters: []

VDAC_DecLoss.quantizer_dropout: 0.1
VDAC_DecLoss.full_codebook_rate: 0.1
VDAC_DecLoss.alpha_dist: 1.0


VDAC_DecLoss.use_gumbel: false
VDAC_DecLoss.use_learnable_alpha: false
VDAC_DecLoss.use_residual_norm_loss: false