$include:
  - conf/base.yml
  - conf/1gpu.yml

amp: false
batch_size: 12
val_batch_size: 12

num_iters: 200000
save_iters: []

VDAC_DecLoss.quantizer_dropout: 0.0
VDAC_DecLoss.full_codebook_rate: 0.0

VDAC_DecLoss.codebook_size: 1024
# VDAC_DecLoss.alpha_dist: 1.0


VDAC_DecLoss.stop_gradient: true
VDAC_DecLoss.sampling_mode: 'bernoulli'
VDAC_DecLoss.use_learnable_alpha: true


VDAC_DecLoss.use_residual_norm_loss: false

## mel_forward/loss는 masked된 샘플에 대해서도 계산하므로, 높은 depth에 dummy 값이 껴 있을 가능성이 높다.