$include:
  - conf/private/base_p.yml
  - conf/private/1gpu_p.yml

num_iters: 800000
save_iters: []

batch_size: 8
val_batch_size: 8


DACImpAdaLevel.quantizer_dropout: 0.25 # 2
DACImpAdaLevel.full_codebook_rate: 0.2 # 1
DACImpAdaLevel.use_framewise_masking: false

DACImpAdaLevel.n_codebooks: 8
DACImpAdaLevel.imp_model_ver: "v3"
DACImpAdaLevel.random_level: true
DACImpAdaLevel.random_range: 0

lambdas:
  mel/loss: 15.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0
  # vq/rate_loss: 0.5  ## [0.0001, 0.2] * 15 * 33 = [0.05, 100.]
  # vq/rate_threshold: 3
  vq/imp_map_level_loss: 0.0  ## imp_map_level_loss / imp_thres_loss 둘 중 하나만 사용.
  vq/imp_map_thres_loss: 0.3

# train/AudioDataset.duration: 1.0

# resume: true
# tag: 'best'
# load_weights: true