$include:
  - conf/private/base_p.yml
  - conf/private/1gpu_p.yml

DAC.quantizer_dropout: 0.5
DAC.n_codebooks: 8
DAC.quantizer_loss: 'l2'


amp: false
batch_size: 16
val_batch_size: 16

num_iters: 200000
save_iters: []
