$include:
  - conf/private/base_p.yml
  - conf/private/1gpu_p.yml

amp: false
batch_size: 32
val_batch_size: 32

DAC.quantizer_dropout: 0.5
DAC.quantizer_loss: 'l2'
# DAC.n_codebooks: 8



num_iters: 200000
save_iters: []
