$include:
  - conf/private/base_p.yml
  - conf/private/1gpu_p.yml

amp: false
batch_size: 32
val_batch_size: 32

num_iters: 200000
save_iters: []

VDAC2.quantizer_dropout: 0.0
VDAC2.full_codebook_rate: 0.0
# VDAC.alpha_dist: 1.0

VDAC2.use_learnable_alpha: true
# VDAC.residual_norm_loss: 'normalized_l2'
VDAC2.quantizer_loss: 'l2'
VDAC2.ftn_version: 'v2'

resume: true
load_weights: true
