$include:
  - conf/a100/base_a.yml
  - conf/a100/1gpu_a.yml

amp: false
batch_size: 64
val_batch_size: 64

num_iters: 200000
save_iters: []

VDAC5.quantizer_dropout: 0.0
VDAC5.full_codebook_rate: 0.2

VDAC5.use_framewise_masking: false # fixdrop
VDAC5.cumulative_p: false # skip