$include:
  - conf/a100/base_a.yml
  - conf/a100/1gpu_a.yml

amp: false
batch_size: 64
val_batch_size: 64

num_iters: 200000
save_iters: []

VDAC3.quantizer_dropout: 0.4
VDAC3.full_codebook_rate: 0.0
# VDAC.alpha_dist: 1.0

VDAC3.use_learnable_alpha: true
# VDAC.residual_norm_loss: 'normalized_l2'
# VDAC3.quantizer_loss: 'l2'
# VDAC3.ftn_version: 'v2'
VDAC3.latents_to_prob: 'v1'
load_pretrained: true
fix_generator_iters: 1000


# VolumeNorm.db: [const, -16]
# VolumeNorm.prob: 0.1

VolumeChange.db: ["uniform", -100.0, 0.0]
VolumeChange.prob: 0.1

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.0
build_transform.augment:
  - Identity
build_transform.postprocess:
  - VolumeChange
  - RescaleAudio
  - ShiftPhase
  # - VolumeNorm