$include:
  - conf/a100/base_a.yml
  - conf/a100/1gpu_a.yml

amp: false
batch_size: 2
val_batch_size: 2

num_iters: 500000
save_iters: []

DAC.quantizer_dropout: 0.5
DAC.n_codebooks: 8

# resume: true
# load_weights: true
