$include:
  - conf/private/base_p.yml
  - conf/private/1gpu_p.yml

amp: false
batch_size: 8
val_batch_size: 8

num_iters: 800000
save_iters: []

DAC.quantizer_dropout: 0.5
DAC.n_codebooks: 8

# resume: true
# load_weights: true
