$include:
  - conf/abci/base_abci.yml
  - conf/abci/dataset_s.yml 
  # - conf/abci/dataset_g.yml  # - conf/abci/1gpu_abci.yml

# amp: false
batch_size: 32
val_batch_size: 8
# num_workers: 8


num_iters: 300000
save_iters: [100000, 200000]

DAC.quantizer_dropout: 0.5
DAC.n_codebooks: 8

# resume: true
# tag: 'latestl
# load_weights: true
load_pretrained: true
load_pretrained_path: 'ckpt_pre/weights_44khz_8kbps_0.0.1.pth'
# n_codebooks: 8
fix_generator_iters: 10000

