$include:
  - conf/abci/base_abci.yml
  - conf/abci/dataset_s.yml
  # - conf/abci/1gpu_abci.yml

# amp: false
batch_size: 32
val_batch_size: 8
# num_workers: 8


# num_iters: 800000
num_iters: 300002
save_iters: [200000, 300000, 500000]

DAC.quantizer_dropout: 0.5
DAC.n_codebooks: 16

# resume: true
# tag: 'latestl
# load_weights: true



## eval pretrained dac
# resume: false
# load_weights: false
# load_pretrained: true
