$include:
  - conf/abci/base_abci.yml
  - conf/abci/dataset_s.yml
  # - conf/abci/1gpu_abci.yml

# amp: false
batch_size: 32
val_batch_size: 8
# num_workers: 8


# num_iters: 800000
# save_iters: [200000, 500000]
num_iters: 300000
save_iters: [200000]

DAC.quantizer_dropout: 0.5
DAC.n_codebooks: 8

# resume: true
# tag: '200k'
# load_weights: true


## eval pretrained dac
# resume: false
# load_weights: false
# load_pretrained: true


train/build_dataset.folders:
        speech_fb:
                - /scratch/acg17028ub/data/DAPS/Sampled/train/
        speech_hq:
                - /scratch/acg17028ub/data/VCTK/Sampled/VCTK-Corpus/wav48/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/vctk_wav48_silence_trimmed/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/read_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/french_speech/
        speech_uq:
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/emotional_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/german_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/russian_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/spanish_speech/
                - /scratch/acg17028ub/data/Common_Voice/Sampled/cv-corpus-17.0-2024-03-15/en/clips/
        # music_hq:
        #         - /scratch/acg17028ub/data/MUSDB/Sampled/train/
        # music_uq:
        #         - /scratch/acg17028ub/data/JAMENDO/Sampled/
        # general:
        #         # - /scratch/acg17028ub/user/koichi/backups/share/dataset/audio/audioset/audioset_tagging_cnn/audios/audioset/train/wav_44k/
        #         - /groups/gce50978/user/koichi/backups/share/dataset/audio/audioset/audioset_tagging_cnn/audios/audioset/train/wav_44k/
        #         - /scratch/acg17028ub/data/AudioSet/Sampled/Balanced_Train/

val/build_dataset.folders:
        speech_hq:
                - /scratch/acg17028ub/data/DAPS/Sampled/val/
        # music_hq:
        #         - /scratch/acg17028ub/data/MUSDB/Sampled/test/
        # general:
        #         - /scratch/acg17028ub/data/AudioSet/Sampled/eval/

test/build_dataset.folders:
        speech_hq:
                - /scratch/acg17028ub/data/DAPS/Sampled/test/
        # music_hq:
        #         - /scratch/acg17028ub/data/MUSDB/Sampled/test/
        # general:
        #         - /scratch/acg17028ub/data/AudioSet/Sampled/eval/