#xx
$include:
  - conf/abci/base_abci.yml
  - conf/abci/dataset_s.yml
  # - conf/abci/dataset_g.yml
  # - conf/abci/1gpu_abci.yml
## DACImp -> DACImpGrad 수정: config제대로 함. 
## 

## 원래 논문:
## ablation: bs 12, 250k iter
## final model: bs 72, 400k iter

num_iters: 300000  
save_iters: [200000]

## 개당=> ㅇㅇ. 16/4 = 개당 4. => 대충 몇 정도?
## 개당 8 => 다른 gpu에선 20000 먹었음.
## 개당 6 해 봅시다. => 총 24
batch_size: 32
val_batch_size: 8

## ALMOST COSINE

## 4 = 32 * 0.125

DACImpGrad.quantizer_dropout: 0.0  ####! 0
DACImpGrad.full_codebook_rate: 0.25 ####! 8  ## THIS
# DACImpGrad.full_codebook_rate: 0.0 ####! 0
DACImpGrad.use_framewise_masking: false

DACImpGrad.n_codebooks: 8
DACImpGrad.imp_model_ver: "v2_2"
DACImpGrad.random_level: 6.0  ####!  x2, x4
# DACImpGrad.random_range: 0

# DACImpGrad.random_exp: [0, 1,'lognormal_straight']
# DACImpGrad.random_exp: [0.02, 50, 'loguniform_straight']  ## This
DACImpGrad.imp2mask_alpha: 2  ###$ we have to set this
DACImpGrad.imp2mask_func: "logcosh_ref"  # 'sigmoid', 'tanh', 'square' ###$
# rate_loss_func: L2  ## This

lambdas: ## For generator. 
  mel/loss: 15.0
  # mel/loss_l2: 0.0  ####!
  # l2/loss: 2.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0

  
  vq/rate_loss: 2  ####!
        ## [0.0001, 0.2] * 15 * 33 = [0.05, 100.]
  vq/rate_threshold: 0 ####!

# # Loss setup

train/build_dataset.folders:
        speech_fb:
                - /scratch/acg17028ub/data/DAPS/Sampled/train/
        speech_hq:
                - /scratch/acg17028ub/data/VCTK/Sampled/VCTK-Corpus/wav48/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/vctk_wav48_silence_trimmed/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/read_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/french_speech/
        speech_uq:
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/emotional_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/german_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/russian_speech/
                - /scratch/acg17028ub/data/DNS_Challenge/Sampled/spanish_speech/
                - /scratch/acg17028ub/data/Common_Voice/Sampled/cv-corpus-17.0-2024-03-15/en/clips/
        # music_hq:
        #         - /scratch/acg17028ub/data/MUSDB/Sampled/train/
        # music_uq:
        #         - /scratch/acg17028ub/data/JAMENDO/Sampled/
        # general:
        #         # - /scratch/acg17028ub/user/koichi/backups/share/dataset/audio/audioset/audioset_tagging_cnn/audios/audioset/train/wav_44k/
        #         - /groups/gce50978/user/koichi/backups/share/dataset/audio/audioset/audioset_tagging_cnn/audios/audioset/train/wav_44k/
        #         - /scratch/acg17028ub/data/AudioSet/Sampled/Balanced_Train/

val/build_dataset.folders:
        speech_hq:
                - /scratch/acg17028ub/data/DAPS/Sampled/val/
        # music_hq:
        #         - /scratch/acg17028ub/data/MUSDB/Sampled/test/
        # general:
        #         - /scratch/acg17028ub/data/AudioSet/Sampled/eval/

test/build_dataset.folders:
        speech_hq:
                - /scratch/acg17028ub/data/DAPS/Sampled/test/
        # music_hq:
        #         - /scratch/acg17028ub/data/MUSDB/Sampled/test/
        # general:
        #         - /scratch/acg17028ub/data/AudioSet/Sampled/eval/